# Generated by Django 4.1.3 on 2022-12-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('yaratgan', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('toifalar', models.CharField(max_length=55)),
                ('fotografiya', models.CharField(max_length=30)),
                ('tegs', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('shaharlar', models.CharField(max_length=255)),
                ('fasl', models.CharField(max_length=255)),
                ('rasm', models.CharField(max_length=255)),
                ('vidiografiya', models.CharField(max_length=255)),
                ('raqam', models.IntegerField(default=1)),
                ('raqamcha', models.IntegerField(default=1)),
                ('kubok', models.IntegerField(default=1)),
                ('lop', models.IntegerField(default=1)),
                ('mening', models.IntegerField(default=1)),
                ('rasmcha', models.CharField(max_length=255)),
            ],
        ),
    ]
