# Generated by Django 4.1.3 on 2022-12-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(max_length=255)),
                ('yaratgan', models.IntegerField(max_length=255)),
            ],
        ),
    ]
