# Generated by Django 4.1.3 on 2022-12-05 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_toifalar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fotografiya',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
