# Generated by Django 4.1.3 on 2022-12-05 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_fotografiya'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tegs',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
