# Generated by Django 4.1.3 on 2022-12-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_fasl_post_rasm_post_shaharlar_post_vidiografiya'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kubok',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='lop',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='mening',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='raqam',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='raqamcha',
            field=models.IntegerField(default=1),
        ),
    ]
